# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = cube
DESTDIR = ./debug
QT += gui core widgets
CONFIG += debug
DEFINES += _WINDOWS _UNICODE WIN64 _WINDOWS _UNICODE WIN64
LIBS += -lshell32
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += .
include(cube.pri)
